### ISSUE TITLE
部分机子列表滚动出错的问题

### ISSUE THREAD

**Issue by karonl** [lovetuzitong/MultiImageSelector#11]
java.lang.NullPointerException: Attempt to invoke virtual method 'char[] java.lang.String.toCharArray()' on a null object reference
            at java.io.File.fixSlashes(File.java:185)
            at java.io.File.<init>(File.java:134)
            at me.nereo.multi_image_selector.utils.TimeUtils.formatPhotoDate(TimeUtils.java:27)
            at me.nereo.multi_image_selector.MultiImageSelectorFragment$3.onScroll(MultiImageSelectorFragment.java:211)

出错都是在new File(path)，猜测是部分图片本身有错的问题，在朋友的日常使用机子上发现。不保证其他安装者不会有出错的图片，所有在new File时候判断 if(path != null) 可避免程序崩溃，

**Comment by GlimmerYang** [comment]
我感觉像是系统调用GC的时候，把数据回收掉了，我打开不保留活动的开关就必现闪退～～
