### ISSUE TITLE
点击左下角“所有照片”报错

### ISSUE THREAD

**Issue by shengoo** [lovetuzitong/MultiImageSelector#14]
在FragmentActivity中调用的

```
Intent intent = new Intent(MainActivity.this, MultiImageSelectorActivity.class);

// 是否显示调用相机拍照
intent.putExtra(MultiImageSelectorActivity.EXTRA_SHOW_CAMERA, true);

// 最大图片选择数量
intent.putExtra(MultiImageSelectorActivity.EXTRA_SELECT_COUNT, 9);

// 设置模式 (支持 单选/MultiImageSelectorActivity.MODE_SINGLE 或者 多选/MultiImageSelectorActivity.MODE_MULTI)
intent.putExtra(MultiImageSelectorActivity.EXTRA_SELECT_MODE, MultiImageSelectorActivity.MODE_MULTI);

startActivityForResult(intent, Constants.PICK_IMAGE_REQUEST_CODE);
```

```
@Override
    protected void onActivityResult(int requestCode, int resultCode, Intent data) {

        super.onActivityResult(requestCode, resultCode, data);
        if(requestCode == Constants.PICK_IMAGE_REQUEST_CODE){
            if(resultCode == RESULT_OK){
                // 获取返回的图片列表
                List<String> path = data.getStringArrayListExtra(MultiImageSelectorActivity.EXTRA_RESULT);
                // 处理你自己的逻辑 ....
                for(String pic:path){
                    System.out.println("pic:" + pic);
                }
            }
        }
    }
```

```
06-06 00:47:03.093  12159-12159/com.sheng00.app.hu I/dalvikvm﹕ Could not find method android.widget.PopupWindow.showAsDropDown, referenced from method android.support.v7.internal.widget.AppCompatPopupWindow.showAsDropDown
06-06 00:47:03.093  12159-12159/com.sheng00.app.hu W/dalvikvm﹕ VFY: unable to resolve virtual method 12719: Landroid/widget/PopupWindow;.showAsDropDown (Landroid/view/View;III)V
06-06 00:47:03.093  12159-12159/com.sheng00.app.hu D/dalvikvm﹕ VFY: replacing opcode 0x6f at 0x000f
06-06 00:47:03.093  12159-12159/com.sheng00.app.hu I/dalvikvm﹕ Could not find method android.content.res.TypedArray.getChangingConfigurations, referenced from method android.support.v7.internal.widget.TintTypedArray.getChangingConfigurations
06-06 00:47:03.093  12159-12159/com.sheng00.app.hu W/dalvikvm﹕ VFY: unable to resolve virtual method 616: Landroid/content/res/TypedArray;.getChangingConfigurations ()I
06-06 00:47:03.093  12159-12159/com.sheng00.app.hu D/dalvikvm﹕ VFY: replacing opcode 0x6e at 0x0002
06-06 00:47:03.093  12159-12159/com.sheng00.app.hu I/dalvikvm﹕ Could not find method android.content.res.TypedArray.getType, referenced from method android.support.v7.internal.widget.TintTypedArray.getType
06-06 00:47:03.093  12159-12159/com.sheng00.app.hu W/dalvikvm﹕ VFY: unable to resolve virtual method 638: Landroid/content/res/TypedArray;.getType (I)I
06-06 00:47:03.093  12159-12159/com.sheng00.app.hu D/dalvikvm﹕ VFY: replacing opcode 0x6e at 0x0002
06-06 00:47:03.093  12159-12159/com.sheng00.app.hu W/dalvikvm﹕ method Landroid/support/v7/internal/widget/ListViewCompat;.lookForSelectablePosition incorrectly overrides package-private method with same name in Landroid/widget/ListView;
06-06 00:47:03.133  12159-12159/com.sheng00.app.hu D/AndroidRuntime﹕ Shutting down VM
06-06 00:47:03.133  12159-12159/com.sheng00.app.hu W/dalvikvm﹕ threadid=1: thread exiting with uncaught exception (group=0x3c9b3ad8)
06-06 00:47:03.143  12159-12159/com.sheng00.app.hu E/AndroidRuntime﹕ FATAL EXCEPTION: main
    java.lang.NullPointerException
            at android.support.v7.internal.widget.ListViewCompat.drawableStateChanged(ListViewCompat.java:91)
            at android.view.View.refreshDrawableState(View.java:14613)
            at android.view.View.dispatchAttachedToWindow(View.java:12170)
            at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2454)
            at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2461)
            at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1207)
            at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1004)
            at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5481)
            at android.view.Choreographer$CallbackRecord.run(Choreographer.java:749)
            at android.view.Choreographer.doCallbacks(Choreographer.java:562)
            at android.view.Choreographer.doFrame(Choreographer.java:532)
            at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:735)
            at android.os.Handler.handleCallback(Handler.java:730)
            at android.os.Handler.dispatchMessage(Handler.java:92)
            at android.os.Looper.loop(Looper.java:137)
            at android.app.ActivityThread.main(ActivityThread.java:5136)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:525)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:740)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:556)
            at dalvik.system.NativeStart.main(Native Method)
```

**Comment by shengoo** [comment]
apptheme 的问题

**Comment by kkm** [comment]
I found this how to fix
style.xml

```
<style name="AppThemeFixCrash" parent="Theme.AppCompat.Light.DarkActionBar"/>
```

and

Manifest.xml

```
        <activity
            android:name="me.nereo.multi_image_selector.MultiImageSelectorActivity"
            android:configChanges="orientation|screenSize"
            android:theme="@style/AppThemeFixCrash"/>
```

happy coding :+1:

**Comment by ghost** [comment]
额没有看，
