### ISSUE TITLE
android 9.0点击相机拍照崩溃 报 FileUriExposedException

### ISSUE THREAD

**Issue by FngLai** [lovetuzitong/MultiImageSelector#157]

**Comment by zhuangzeqin** [comment]
android.os.FileUriExposedException: file:///storage/emulated/0/DCIM/IMG_4018508276357708395.jpg exposed beyond app through ClipData.Item.getUri()

**Comment by zhuangzeqin** [comment]
at me.nereo.multi_image_selector.MultiImageSelectorFragment.showCameraAction(MultiImageSelectorFragment.java:321)
        at me.nereo.multi_image_selector.MultiImageSelectorFragment.access$400(MultiImageSelectorFragment.java:56)
        at me.nereo.multi_image_selector.MultiImageSelectorFragment$2.onItemClick(MultiImageSelectorFragment.java:162)
