### ISSUE TITLE
Crack when rotate to device on Tablet

### ISSUE THREAD

**Issue by Leminity** [lovetuzitong/MultiImageSelector#2]
Hello.

I'm applying to your source.

I find problem to use MultiImageSelectorActivity when rotate device.

Append exception message this.

thx.

_Device_ : Samsung Galaxy Tab 10.1
_OS Version_ : 4.4.4 Kitkat

---

_Exception Messages_

``` java
java.lang.IllegalArgumentException: At least one dimension has to be positive number.
            at com.squareup.picasso.Request$Builder.resize(Request.java:305)
            at com.squareup.picasso.RequestCreator.resize(RequestCreator.java:219)
            at me.nereo.multi_image_selector.adapter.ImageGridAdapter$ViewHolde.bindData(ImageGridAdapter.java:255)
            at me.nereo.multi_image_selector.adapter.ImageGridAdapter.getView(ImageGridAdapter.java:214)
            at android.widget.AbsListView.obtainView(AbsListView.java:2800)
            at android.widget.GridView.onMeasure(GridView.java:1065)
            at android.view.View.measure(View.java:17619)
            at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:719)
            at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:455)
            at android.view.View.measure(View.java:17619)
            at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5428)
            at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
            at android.view.View.measure(View.java:17619)
            at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5428)
            at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
            at android.view.View.measure(View.java:17619)
            at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5428)
            at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1410)
            at android.widget.LinearLayout.measureVertical(LinearLayout.java:695)
            at android.widget.LinearLayout.onMeasure(LinearLayout.java:588)
            at android.view.View.measure(View.java:17619)
            at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5428)
            at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
            at android.view.View.measure(View.java:17619)
            at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5428)
            at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1410)
            at android.widget.LinearLayout.measureVertical(LinearLayout.java:695)
            at android.widget.LinearLayout.onMeasure(LinearLayout.java:588)
            at android.view.View.measure(View.java:17619)
            at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5428)
            at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
            at com.android.internal.policy.impl.PhoneWindow$DecorView.onMeasure(PhoneWindow.java:2588)
            at android.view.View.measure(View.java:17619)
            at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2328)
            at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1436)
            at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1634)
            at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1294)
            at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6725)
            at android.view.Choreographer$CallbackRecord.run(Choreographer.java:813)
            at android.view.Choreographer.doCallbacks(Choreographer.java:613)
            at android.view.Choreographer.doFrame(Choreographer.java:583)
            at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:799)
            at android.os.Handler.handleCallback(Handler.java:733)
            at android.os.Handler.dispatchMessage(Handler.java:95)
            at android.os.Looper.loop(Looper.java:146)
            at android.app.ActivityThread.main(ActivityThread.java:5744)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:515)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1291)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1107)
            at dalvik.system.NativeStart.main(Native Method)
```

**Comment by Leminity** [comment]
I fixed to customize.

customize code is this.
- MultiImageSelectorFragment.java
  1. extract method(method sig : setGlobalOnListenerForRotation()) to addOnGlobalListener Logic from onViewCreated.
  2. call setGlobalOnListenerForRotation() in onViewCreated.
  3. override onConfigurationChanged() in MultiImageSelectorFragment. and call addOnGlobalListener Logic method.

**Extract Method code**

``` java
private void setGlobalOnListenerForRotation(){
        mGridView.getViewTreeObserver().addOnGlobalLayoutListener(new ViewTreeObserver.OnGlobalLayoutListener() {
            @Override @TargetApi(Build.VERSION_CODES.JELLY_BEAN)
            public void onGlobalLayout() {
                final int numCount = mGridView.getNumColumns();
                final int columnSpace = getResources().getDimensionPixelOffset(R.dimen.space_size);
                int columnWidth = (mGridView.getWidth() - columnSpace*(numCount-1)) / numCount;
                mImageAdapter.setItemSize(columnWidth);
                if(Build.VERSION.SDK_INT >= Build.VERSION_CODES.JELLY_BEAN){
                    mGridView.getViewTreeObserver().removeOnGlobalLayoutListener(this);
                }else{
                    mGridView.getViewTreeObserver().removeGlobalOnLayoutListener(this);
                }
            }
        });
    }
```

**Comment by lovetuzitong** [comment]
@Leminity Thanks for your contribution :smile:

**Comment by Leminity** [comment]
@lovetuzitong you're welcome. Many thanks for this project. i'll close this.
