### ISSUE TITLE
打开就crash 三星s5 cm android 5.0

### ISSUE THREAD

**Issue by jianghao1123** [lovetuzitong/MultiImageSelector#21]
Process: me.nereo.multiimageselector, PID: 14832
    java.lang.NullPointerException: Attempt to invoke virtual method 'char[] java.lang.String.toCharArray()' on a null object reference
            at java.io.File.fixSlashes(File.java:185)
            at java.io.File.<init>(File.java:134)
            at me.nereo.multi_image_selector.MultiImageSelectorFragment$8.onLoadFinished(MultiImageSelectorFragment.java:489)
            at me.nereo.multi_image_selector.MultiImageSelectorFragment$8.onLoadFinished(MultiImageSelectorFragment.java:449)
            at android.support.v4.app.LoaderManagerImpl$LoaderInfo.callOnLoadFinished(LoaderManager.java:427)
            at android.support.v4.app.LoaderManagerImpl$LoaderInfo.onLoadComplete(LoaderManager.java:395)
            at android.support.v4.content.Loader.deliverResult(Loader.java:104)
            at android.support.v4.content.CursorLoader.deliverResult(CursorLoader.java:73)
            at android.support.v4.content.CursorLoader.deliverResult(CursorLoader.java:35)
            at android.support.v4.content.AsyncTaskLoader.dispatchOnLoadComplete(AsyncTaskLoader.java:223)
            at android.support.v4.content.AsyncTaskLoader$LoadTask.onPostExecute(AsyncTaskLoader.java:61)
            at android.support.v4.content.ModernAsyncTask.finish(ModernAsyncTask.java:461)
            at android.support.v4.content.ModernAsyncTask.access$500(ModernAsyncTask.java:47)
            at android.support.v4.content.ModernAsyncTask$InternalHandler.handleMessage(ModernAsyncTask.java:474)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5256)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:898)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:693)

**Comment by henry-newbie** [comment]
我也碰到了这个问题，
MultiImageSelectorFragment的442行
String path = data.getString(data.getColumnIndexOrThrow(IMAGE_PROJECTION[0]));
获取到的path是null

**Comment by henry-newbie** [comment]
最后这样解决了，如果path为null就跳过
