### ISSUE TITLE
点击“All Images”时空指针错误

### ISSUE THREAD

**Issue by sjd168** [lovetuzitong/MultiImageSelector#38]
12-29 14:50:58.304  10003-10003/com.itojoy.book E/AndroidRuntime﹕ FATAL EXCEPTION: main
    Process: com.itojoy.book, PID: 10003
    java.lang.NullPointerException
            at android.support.v7.internal.widget.ListViewCompat.drawableStateChanged(ListViewCompat.java:91)
            at android.view.View.refreshDrawableState(View.java:15166)
            at android.view.View.dispatchAttachedToWindow(View.java:12621)
            at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2458)
            at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2465)
            at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1274)
            at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1057)
            at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5666)
            at android.view.Choreographer$CallbackRecord.run(Choreographer.java:761)
            at android.view.Choreographer.doCallbacks(Choreographer.java:574)
            at android.view.Choreographer.doFrame(Choreographer.java:544)
            at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:747)
            at android.os.Handler.handleCallback(Handler.java:733)
            at android.os.Handler.dispatchMessage(Handler.java:95)
            at android.os.Looper.loop(Looper.java:136)
            at android.app.ActivityThread.main(ActivityThread.java:5072)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:515)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:609)
            at dalvik.system.NativeStart.main(Native Method)

**Comment by sjd168** [comment]
刚刚我发现加了这个库https://github.com/android-cjj/Android-MaterialRefreshLayout,居然就不崩溃了
