### ISSUE TITLE
click mCategoryText crash

### ISSUE THREAD

**Issue by liuxu0703** [lovetuzitong/MultiImageSelector#4]
crash occur when click mCategoryText. for now i did not figure out why.
点击目录选择按钮崩溃.

04-23 09:56:08.888  2878  2878 E AndroidRuntime: java.lang.NullPointerException
04-23 09:56:08.888  2878  2878 E AndroidRuntime:    at android.support.v7.internal.widget.ListViewCompat.drawableStateChanged(ListViewCompat.java:91)
04-23 09:56:08.888  2878  2878 E AndroidRuntime:    at android.view.View.refreshDrawableState(View.java:15136)
04-23 09:56:08.888  2878  2878 E AndroidRuntime:    at android.view.View.dispatchAttachedToWindow(View.java:12608)
04-23 09:56:08.888  2878  2878 E AndroidRuntime:    at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2458)
04-23 09:56:08.888  2878  2878 E AndroidRuntime:    at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1247)
04-23 09:56:08.888  2878  2878 E AndroidRuntime:    at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1015)
04-23 09:56:08.888  2878  2878 E AndroidRuntime:    at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5717)
04-23 09:56:08.888  2878  2878 E AndroidRuntime:    at android.view.Choreographer$CallbackRecord.run(Choreographer.java:761)
04-23 09:56:08.888  2878  2878 E AndroidRuntime:    at android.view.Choreographer.doCallbacks(Choreographer.java:574)
04-23 09:56:08.888  2878  2878 E AndroidRuntime:    at android.view.Choreographer.doFrame(Choreographer.java:544)
04-23 09:56:08.888  2878  2878 E AndroidRuntime:    at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:747)
04-23 09:56:08.888  2878  2878 E AndroidRuntime:    at android.os.Handler.handleCallback(Handler.java:733)
04-23 09:56:08.888  2878  2878 E AndroidRuntime:    at android.os.Handler.dispatchMessage(Handler.java:95)
04-23 09:56:08.888  2878  2878 E AndroidRuntime:    at android.os.Looper.loop(Looper.java:136)
04-23 09:56:08.888  2878  2878 E AndroidRuntime:    at android.app.ActivityThread.main(ActivityThread.java:5137)
04-23 09:56:08.888  2878  2878 E AndroidRuntime:    at java.lang.reflect.Method.invokeNative(Native Method)
04-23 09:56:08.888  2878  2878 E AndroidRuntime:    at java.lang.reflect.Method.invoke(Method.java:515)
04-23 09:56:08.888  2878  2878 E AndroidRuntime:    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:795)
04-23 09:56:08.888  2878  2878 E AndroidRuntime:    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:611)
04-23 09:56:08.888  2878  2878 E AndroidRuntime:    at dalvik.system.NativeStart.main(Native Method)

**Comment by liuxu0703** [comment]
call setListSelector() explicitly will solve the problem. seems that some device failed to provider a default selector for android.support.v7.internal.widget.ListViewCompat.
@lovetuzitong maybe you can add this line to the code.

mFolderPopupWindow.setListSelector(...);

**Comment by Little-Huang** [comment]
The same problem with you 

resolved 

thanks

Thanks

**Comment by YaakovHuang** [comment]
the same problem with you

resolved

thanks
