### ISSUE TITLE
空指针异常。

### ISSUE THREAD

**Issue by ContinueCoding** [lovetuzitong/MultiImageSelector#43]
在图片选择页面点击左下角“所有照片”切换其他目录时报NullPointerException了。堆栈信息如下：
FATAL EXCEPTION: main
                                                           java.lang.NullPointerException
                                                               at me.nereo.multi_image_selector.adapter.FolderAdapter$ViewHolder.bindData(FolderAdapter.java:155)
                                                               at me.nereo.multi_image_selector.adapter.FolderAdapter.getView(FolderAdapter.java:96)
                                                               at android.support.v7.internal.widget.ListViewCompat.measureHeightOfChildrenCompat(ListViewCompat.java:290)
                                                               at android.support.v7.widget.ListPopupWindow.buildDropDown(ListPopupWindow.java:1200)
                                                               at android.support.v7.widget.ListPopupWindow.show(ListPopupWindow.java:584)
                                                               at me.nereo.multi_image_selector.MultiImageSelectorFragment$1.onClick(MultiImageSelectorFragment.java:157)
                                                               at android.view.View.performClick(View.java:4367)
                                                               at android.view.View$PerformClick.run(View.java:17984)
                                                               at android.os.Handler.handleCallback(Handler.java:725)
                                                               at android.os.Handler.dispatchMessage(Handler.java:92)
                                                               at android.os.Looper.loop(Looper.java:137)
                                                               at android.app.ActivityThread.main(ActivityThread.java:5297)
                                                               at java.lang.reflect.Method.invokeNative(Native Method)
                                                               at java.lang.reflect.Method.invoke(Method.java:511)
                                                               at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1102)
                                                               at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:869)
                                                               at dalvik.system.NativeStart.main(Native Method)

**Comment by lovetuzitong** [comment]
tks
