### ISSUE TITLE
拍照时io流异常

### ISSUE THREAD

**Issue by liuyanji** [lovetuzitong/MultiImageSelector#68]
因为io流异常，所以没进 if(mTmpFile != null && mTmpFile.exists()) {，而是进入的else，图片错误
 java.io.IOException: open failed: EACCES (Permission denied)
  at java.io.File.createNewFile(File.java:940)
 at java.io.File.createTempFile(File.java:1005)
  at cn.studyjams.s1.sj10.licat.imageselect.utils.FileUtils.createTmpFile(FileUtils.java:35)
    at     cn.studyjams.s1.sj10.licat.imageselect.MultiImageSelectorFragment.showCameraAction(MultiImageSelectorFragment.java:344)
  at cn.studyjams.s1.sj10.licat.imageselect.MultiImageSelectorFragment.access$400(MultiImageSelectorFragment.java:52)
      at cn.studyjams.s1.sj10.licat.imageselect.MultiImageSelectorFragment$3.onItemClick(MultiImageSelectorFragment.java:189)

**Comment by lovetuzitong** [comment]
`java.io.IOException: open failed: EACCES (Permission denied)` 
see [Requesting Permissions at Run Time](http://developer.android.com/training/permissions/requesting.html)
