### ISSUE TITLE
进入选区图片界面时报错。。。。

### ISSUE THREAD

**Issue by syg13579** [lovetuzitong/MultiImageSelector#71]
貌似是没有找到OKHttp，求作者解决，总不能需要我在工程中自己添加OKHeep吧，或是这是由其他问题引起的

Process: com.rock.androidsupportlib.app, PID: 17689
    java.lang.RuntimeException: Picasso detected an unsupported OkHttp on the classpath.
    To use OkHttp with this version of Picasso, you'll need:
    1. com.squareup.okhttp:okhttp:1.6.0 (or newer)
    2. com.squareup.okhttp:okhttp-urlconnection:1.6.0 (or newer)
    Note that OkHttp 2.0.0+ is supported!
            at com.squareup.picasso.Utils.createDefaultDownloader(Utils.java:251)
            at com.squareup.picasso.Picasso$Builder.build(Picasso.java:754)
            at com.squareup.picasso.Picasso.with(Picasso.java:597)
            at me.nereo.multi_image_selector.adapter.ImageGridAdapter$ViewHolder.bindData(ImageGridAdapter.java:225)
            at me.nereo.multi_image_selector.adapter.ImageGridAdapter.getView(ImageGridAdapter.java:187)
            at android.widget.AbsListView.obtainView(AbsListView.java:3147)
            at android.widget.GridView.makeAndAddView(GridView.java:1420)
            at android.widget.GridView.makeRow(GridView.java:370)
            at android.widget.GridView.fillSpecific(GridView.java:581)
            at android.widget.GridView.layoutChildren(GridView.java:1298)
            at android.widget.AbsListView.onLayout(AbsListView.java:2979)
            at android.view.View.layout(View.java:15488)
            at android.view.ViewGroup.layout(ViewGroup.java:4662)
            at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1055)
            at android.view.View.layout(View.java:15488)
            at android.view.ViewGroup.layout(ViewGroup.java:4662)
            at android.widget.FrameLayout.layoutChildren(FrameLayout.java:453)
            at android.widget.FrameLayout.onLayout(FrameLayout.java:388)
            at android.view.View.layout(View.java:15488)
            at android.view.ViewGroup.layout(ViewGroup.java:4662)
            at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1671)
            at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1525)
            at android.widget.LinearLayout.onLayout(LinearLayout.java:1434)
            at android.view.View.layout(View.java:15488)
            at android.view.ViewGroup.layout(ViewGroup.java:4662)
            at android.widget.FrameLayout.layoutChildren(FrameLayout.java:453)
            at android.widget.FrameLayout.onLayout(FrameLayout.java:388)
            at android.view.View.layout(View.java:15488)
            at android.view.ViewGroup.layout(ViewGroup.java:4662)
            at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1671)
            at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1525)
            at android.widget.LinearLayout.onLayout(LinearLayout.java:1434)
            at android.view.View.layout(View.java:15488)
            at android.view.ViewGroup.layout(ViewGroup.java:4662)
            at android.widget.FrameLayout.layoutChildren(FrameLayout.java:453)
            at android.widget.FrameLayout.onLayout(FrameLayout.java:388)
            at android.view.View.layout(View.java:15488)
            at android.view.ViewGroup.layout(ViewGroup.java:4662)
            at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1671)
            at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1525)
            at android.widget.LinearLayout.onLayout(LinearLayout.java:1434)
            at android.view.View.layout(View.java:15488)
            at android.view.ViewGroup.layout(ViewGroup.java:4662)
            at android.widget.FrameLayout.layoutChildren(FrameLayout.java:453)
            at android.widget.FrameLayout.onLayout(FrameLayout.java:388)
            at android.view.View.layout(View.java:15488)
            at android.view.ViewGroup.layout(ViewGroup.java:4662)
            at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2397)
            at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2094)
            at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1066)
            at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6245)
            at android.view.Choreographer$CallbackRecord.run(Choreographer.java:767)
            at android.view.Choreographer.doCallbacks(Choreographer.java:580)
            at android.view.Choreographer.doFrame(Choreographer.java:550)
            at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:753)
            at android.os.Handler.handleCallback(Handler.java:733)
            at android.os.Handler.dispatchMessage(Handler.java:95)
            at android.os.Looper.loop(Looper.java:136)
            at android.app.ActivityThread.main(ActivityThread.java:5117)
            at java.lang.reflect.Method.in

**Comment by lovetuzitong** [comment]
`java.lang.RuntimeException: Picasso detected an unsupported OkHttp on the classpath.` 是指你自己的的项目里面引用了一个`Picasso`不支持的`OkHttp`版本。仔细检查下自己项目的依赖先。

**Comment by yyclang** [comment]
/AndroidRuntime: FATAL EXCEPTION: main
                                                                      java.lang.RuntimeException: Picasso detected an unsupported OkHttp on the classpath.
                                                                      To use OkHttp with this version of Picasso, you'll need:
                                                                      1. com.squareup.okhttp:okhttp:1.6.0 (or newer)
                                                                      2. com.squareup.okhttp:okhttp-urlconnection:1.6.0 (or newer)
                                                                      Note that OkHttp 2.0.0+ is supported!
                                                                          at com.squareup.picasso.Utils.createDefaultDownloader(Utils.java:251)
                                                                          at com.squareup.picasso.Picasso$Builder.build(Picasso.java:754)
                                                                          at com.squareup.picasso.Picasso.with(Picasso.java:597)
                                                                          at me.nereo.multi_image_selector.adapter.ImageGridAdapter$ViewHolder.bindData(ImageGridAdapter.java:225)
                                                                          at me.nereo.multi_image_selector.adapter.ImageGridAdapter.getView(ImageGridAdapter.java:187)
                                                                          at android.widget.AbsListView.obtainView(AbsListView.java:2270)
                                                                          at android.widget.GridView.makeAndAddView(GridView.java:1352)
                                                                          at android.widget.GridView.makeRow(GridView.java:352)
                                                                          at android.widget.GridView.fillSpecific(GridView.java:554)
                                                                          at android.widget.GridView.layoutChildren(GridView.java:1251)
                                                                          at android.widget.AbsListView.onLayout(AbsListView.java:2094)
                                                                          at android.view.View.layout(View.java:14114)
                                                                          at android.view.ViewGroup.layout(ViewGroup.java:4467)
                                                                          at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1021)
                                                                          at android.view.View.layout(View.java:14114)
                                                                          at android.view.ViewGroup.layout(ViewGroup.java:4467)
                                                                          at android.widget.FrameLayout.onLayout(FrameLayout.java:448)
                                                                          at android.view.View.layout(View.java:14114)
                                                                          at android.view.ViewGroup.layout(ViewGroup.java:4467)
                                                                          at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1670)
                                                                          at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1528)
                                                                          at android.widget.LinearLayout.onLayout(LinearLayout.java:1441)
                                                                          at android.view.View.layout(View.java:14114)
                                                                          at android.view.ViewGroup.layout(ViewGroup.java:4467)
                                                                          at android.widget.FrameLayout.onLayout(FrameLayout.java:448)
                                                                          at android.view.View.layout(View.java:14114)
                                                                          at android.view.ViewGroup.layout(ViewGroup.java:4467)
                                                                          at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1670)
                                                                          at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1528)
                                                                          at android.widget.LinearLayout.onLayout(LinearLayout.java:1441)
                                                                          at android.view.View.layout(View.java:14114)
                                                                          at android.view.ViewGroup.layout(ViewGroup.java:4467)
                                                                          at android.widget.FrameLayout.onLayout(FrameLayout.java:448)
                                                                          at android.view.View.layout(View.java:14114)
                                                                          at android.view.ViewGroup.layout(ViewGroup.java:4467)
                                                                          at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1670)
                                                                          at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1528)
                                                                          at android.widget.LinearLayout.onLayout(LinearLayout.java:1441)
                                                                          at android.view.View.layout(View.java:14114)
                                                                          at android.view.ViewGroup.layout(ViewGroup.java:4467)
                                                                          at android.widget.FrameLayout.onLayout(FrameLayout.java:448)
                                                                          at android.view.View.layout(View.java:14114)
                                                                          at android.view.ViewGroup.layout(ViewGroup.java:4467)
                                                                          at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2207)
                                                                          at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1971)
                                                                          at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1152)
                                                                          at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:4966)
                                                                          at android.view.Choreographer$CallbackRecord.run(Choreographer.java:776)
                                                                          at android.view.Choreographer.doCallbacks(Choreographer.java:579)
                                                                          at android.view.Choreographer.doFrame(Choreographer.java:548)
                                                                          at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:762)
                                                                          at android.os.Handler.handleCallback(Handler.java:725)
                                                                          at android.os.Handler.dispatchMessage(Handler.java:92)
                                                                          at android.os.Looper.loop(Looper.java:153)
                                                                          at android.app.ActivityThread.main(ActivityThread.java:5344)
                                                                          at java.lang.reflect.Method.invokeNative(Native Method)
                                                                          at java.lang.reflect.Method.invoke(Method.java:511)
                                                                          at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:833)
                                                                          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:600)
                                                                          at dalvik.system.NativeStart.main(Native Method)
