### ISSUE TITLE
能写出项目适配的SDK版本吗？

### ISSUE THREAD

**Issue by Dave1991** [lovetuzitong/MultiImageSelector#78]
我项目的SDK版本是
compileSdkVersion 23
buildToolsVersion "23.0.3"

```
defaultConfig {
    minSdkVersion 8
    targetSdkVersion 23
}
```

结果报出
java.lang.NoSuchMethodError: No static method checkSelfPermission

**Comment by Dave1991** [comment]
据我所知，checkSelfPermission这是API23才引入的，作者应该对之前的API也做个适配吧。

**Comment by lovetuzitong** [comment]
可以提供下 `StackTrace` 么 ？

**Comment by Dave1991** [comment]
FATAL EXCEPTION: main
                                                                       Process: com.zhongke.neighbour, PID: 23161
                                                                       java.lang.NoSuchMethodError: No static method checkSelfPermission(Landroid/content/Context;Ljava/lang/String;)I in class Landroid/support/v4/content/ContextCompat; or its super classes (declaration of 'android.support.v4.content.ContextCompat' appears in /data/data/com.zhongke.neighbour/files/instant-run/dex/slice-support4_f6dde806a6fd6917fb8d09558b368a26cec6174e-classes.dex)
                                                                           at me.nereo.multi_image_selector.MultiImageSelector.hasPermission(MultiImageSelector.java:97)
                                                                           at me.nereo.multi_image_selector.MultiImageSelector.start(MultiImageSelector.java:78)
                                                                           at com.zhongke.neighbour.home.RepairAddActivity$3.onClick(RepairAddActivity.java:107)
                                                                           at android.view.View.performClick(View.java:4908)
                                                                           at android.view.View$PerformClick.run(View.java:20382)
                                                                           at android.os.Handler.handleCallback(Handler.java:815)
                                                                           at android.os.Handler.dispatchMessage(Handler.java:104)
                                                                           at android.os.Looper.loop(Looper.java:194)
                                                                           at android.app.ActivityThread.main(ActivityThread.java:5692)
                                                                           at java.lang.reflect.Method.invoke(Native Method)
                                                                           at java.lang.reflect.Method.invoke(Method.java:372)
                                                                           at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:959)
                                                                           at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:754)

**Comment by lovetuzitong** [comment]
看堆栈信息，指的是 `android.support.v4.content.ContextCompat` 这个类没有 `ContextCompat. checkSelfPermission` 这个方法。
`ContextCompat`类本身就是`Context`向前兼容的实现。所以问题不是 `项目适配的SDK` 这个问题。
或许是你的support library 的版本太低，导致编译后使用了较低版本的 support library。

**Comment by Dave1991** [comment]
那MultiImageSelector所要求的support library的版本要求多少

Sent with Unibox

**Comment by lovetuzitong** [comment]
`compile 'com.android.support:appcompat-v7:23.4.0'`

**Comment by vincent19921017wang** [comment]
I solve the problem by  compile 'com.android.support:appcompat-v7:23.4.0'
